git add ../spatial analysis & geospacial data science in Python/covid-19-spatial-geo.ipynb
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/05_if-acl.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/07_file-access(Create a script to allow user to add devices) - Version 2.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/07_file-access(Create a script to allow user to add devices).py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/07_file-access(remove Blank Lines).py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/07_file-access.(copy file content into a list variable).py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/07_file-access.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_1.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_2.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_3.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_4.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_5.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_5_testing_routes.PNG"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_6.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_7.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_headers2.pdf"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_route1.json"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/08_parse_json_route2.json"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 1/devices.txt"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/RESTCongWithPostman.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/UpdateConfig-RetrievethsIOS-XE VM's existing running configuration.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/modifyInterfaceConfigurationWithRESConfInPython.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/netconf-w-Python-List Capabilities.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/retrievethsIOS-XE VM's existing running configuration.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/settingUpTheLabEnvironment.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/04_path_trace2.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/2.3.2.1 Lab - Create a Host Inventory in Python.pdf"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/2.3.3.1 Lab - Create a Network Device Inventory in Python.pdf"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/2.3.4.1 Lab - Using the APIC-EM Path Trace API.pdf"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/APIC-EM Topology Page.png"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/Authenticating with the APIC-EM - response.html"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/FLOW-ANALYSIS api.png"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/GetServiceTicketinPython.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/GetServiceTicketinPythonwithFunction.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/Investigate the Network Device Inventory API.png"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/Role Based Access Control with API sandbox.png"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/access_host_.txt"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/access_host_1.txt"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/access_host_2.txt"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/flow-analysis-Id.json"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/get a service ticket in postman"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/inventory response body.json"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/inventory.json"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/my_apic_em_functions.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/my_apic_em_functions2.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/print_devices.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/print_host.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/re-aprendiendo.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/re-aprendiendo2.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/re-aprendiendo3.py"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/use Postman and JSON Viwer to get a network host inventory.json"
git add "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/use Postman to get a network host inventory"
git add Model Driven Programmability - DevnNet20/Cisco IOS-XE/
git add Model Driven Programmability - DevnNet20/Files Scripts Python/
git add _ENTREGAS/
git add contents/
git add ficheros.sh
git add images/
git add subida/
git nota "ProgramacionModernaPython"
git sube