	git add  .vscode/
	cd "Model Driven Programmability - DevnNet20/Activities/M\\303\\263dulo 1/"
	git add  "05_if-acl.py"
	git add  "07_file-access(Create a script to allow user to add devices) - Version 2.py"
	git add  "07_file-access(Create a script to allow user to add devices).py"
	git add  "07_file-access(remove Blank Lines).py"
	git add  "07_file-access.(copy file content into a list variable).py"
	git add  "07_file-access.py"
	git add  "08_parse_json_1.py"
	git add  "08_parse_json_2.py"
	git add  "08_parse_json_3.py"
	git add  "08_parse_json_4.py"
	git add  "08_parse_json_5.py"
	git add  "08_parse_json_5_testing_routes.PNG"
	git add  "08_parse_json_6.py"
	git add  "08_parse_json_7.py"
	git add  "08_parse_json_headers2.pdf"
	git add  "08_parse_json_route1.json"
	git add  "08_parse_json_route2.json"
	git add  "devices.txt"	
	git nota "Mod. 1"
	git sube

	cd "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 2/"
	git add  "RESTCongWithPostman.py"
	git add  "UpdateConfig-RetrievethsIOS-XE VM's existing running configuration.py"
	git add  "modifyInterfaceConfigurationWithRESConfInPython.py"
	git add  "netconf-w-Python-List Capabilities.py"
	git add  "retrievethsIOS-XE VM's existing running configuration.py"
	git add  "settingUpTheLabEnvironment.py"
	git nota "Mod. 2"
	git sube

	cd "Model Driven Programmability - DevnNet20/Activities/M\303\263dulo 3/"
	git add  "04_path_trace2.py"
	git add  "2.3.2.1 Lab - Create a Host Inventory in Python.pdf"
	git add  "2.3.3.1 Lab - Create a Network Device Inventory in Python.pdf"
	git add  "2.3.4.1 Lab - Using the APIC-EM Path Trace API.pdf"
	git add  "APIC-EM Topology Page.png"
	git add  "Authenticating with the APIC-EM - response.html"
	git add  "FLOW-ANALYSIS api.png"
	git add  "GetServiceTicketinPython.py"
	git add  "GetServiceTicketinPythonwithFunction.py"
	git add  "Investigate the Network Device Inventory API.png"
	git add  "Role Based Access Control with API sandbox.png"
	git add  "access_host_.txt"
	git add  "access_host_1.txt"
	git add  "access_host_2.txt"
	git add  "flow-analysis-Id.json"
	git add  "get a service ticket in postman"
	git add  "inventory response body.json"
	git add  "inventory.json"
	git add  "my_apic_em_functions.py"
	git add  "my_apic_em_functions2.py"
	git add  "print_devices.py"
	git add  "print_host.py"
	git add  "re-aprendiendo.py"
	git add  "re-aprendiendo2.py"
	git add  "re-aprendiendo3.py"
	git add  "use Postman and JSON Viwer to get a network host inventory.json"
	git add  "use Postman to get a network host inventory"
	git nota "Mod. 3"

	git add  Model Driven Programmability - DevnNet20/Cisco IOS-XE/*
	git add  Model Driven Programmability - DevnNet20/Files Scripts Python/*
	git add  _ENTREGAS/
	git nota "Model Driven Programmability - DevnNet20"
	git sube