git add "__CONFIGURACION__02.33.30.txt"
git add "__CONFIGURACION__Branch2-Router_02.44.26.txt"
git add "__CONFIGURACION__Branch-Access1_02.44.26.txt"
git add "__CONFIGURACION__Branch-Router1_02.44.26.txt"
git add "__CONFIGURACION__Branch-Router2_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Access1_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Core1_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Core2_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Dist1_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Dist2_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Router1_02.44.26.txt"
git add "__CONFIGURACION__CAMPUS-Router2_02.44.26.txt"
git add "20200402_014810.jpg"
git add "20200404_175428.jpg"
git add "AutomatizationScriptInfoAPIC-EM 60%OK.py"
git add "capabilities.PNG"
git add "ConnectRouterCSR1000-PTE-DE-REVISAR.py"
git add "files.sh"
git add "interface.PNG"
git add "internal-error-Error al borrar loopback2.PNG"
git add "loopback1.PNG"
git add "modelo YANG de las interfaces.PNG"
git add "salida.PNG"
git add "Solo queda Loopback 1.PNG"
git add "tabla de rutas + nueva ruta añadida - no pude sacarlo modo tabla 'bonita' porque con los finales de la U no me da la vida.PNG"
git add "Ver info de loopback1 entero con modelo YANG + menú 5.PNG"
git add "Vuelvo a ejecutarlo y ya elimino a 2 y 3 Loopback.PNG"
git nota "Pruebas y documentos de las pruebas"
git sube