#!/bin/bash
git add "__Ch1_Files.zip"
git add "__Files.sh"
git add "01_hello-world_sol.py"
git add "02_list-dicts.py"
git add "02_list-dicts_sol.py"
git add "03_personal-info_sol.py"
git add "04_if-VLAN_sol.py"
git add "05_if-ACL_sol.py"
git add "06_while-loop_sol.py"
git add "07_file-access_sol.py"
git add "07_file-access_sol_activity.py"
git add "08_parse-json_sol.py"
git add "08_parse-json1_sol.py"
git add "08_parse-json2_sol.py"
git add "08_parse-json3_sol.py"
git add "08_parse-json4_sol.py"
git add "08_parse-json5_sol.py"
git add "08_parse-json6_sol.py"
git add "08_parse-json7_sol.py"
git add "devices.txt"
git nota "Files Scripts Python"
git sube