#!/bin/bash
git add "__fi.sh" 
git add "04_path_trace.py" 
git add "04_path_trace2.py" 
git add "2.3.2.1 Lab - Create a Host Inventory in Python.pdf" 
git add "2.3.3.1 Lab - Create a Network Device Inventory in Python.pdf" 
git add "2.3.4.1 Lab - Using the APIC-EM Path Trace API.pdf" 
git add "access_host_.txt" 
git add "access_host_1.txt" 
git add "access_host_2.txt" 
git add "APIC-EM Topology Page.png" 
git add "Authenticating with the APIC-EM - response.html" 
git add "FLOW-ANALYSIS api.png" 
git add "flow-analysis-Id.json" 
git add "get a service ticket in postman" 
git add "GetServiceTicketinPython.py" 
git add "GetServiceTicketinPythonwithFunction.py" 
git add "inventory response body.json" 
git add "inventory.json" 
git add "Investigate the Network Device Inventory API.png" 
git add "my_apic_em_functions.py" 
git add "my_apic_em_functions2.py" 
git add "print_devices.py" 
git add "print_host.py" 
git add "re-aprendiendo.py" 
git add "re-aprendiendo2.py" 
git add "re-aprendiendo3.py" 
git add "Role Based Access Control with API sandbox.png" 
git add "use Postman and JSON Viwer to get a network host inventory.json" 
git add "use Postman to get a network host inventory"
git nota "Mód. 3"
git sube